{% set name = "analphipy" %}
{% set version = "0.4.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/analphipy-{{ version }}.tar.gz
  sha256: 4d4f1d0b0bb8b7861d714999450cbcc2c798e1a52157e6900beee13571bc6e9e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - attrs
    - docstring-inheritance
    - module-utilities >=0.10.1
    - numpy
    - scipy
    - typing_extensions

test:
  imports:
    - analphipy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/usnistgov/analphipy
  summary: Utilities to perform stat mech analysis of pair potentials
  description: |
    `analphipy` is a python package to calculate metrics for classical models for
    pair potentials. It provides a simple and extendable api for pair potentials
    creation. Several routines to calculate metrics are included in the package.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
